import logger from '@sequential/sequential-logging';
import { delay, withRetry } from '@sequential/async-patterns';
#!/usr/bin/env node

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { detectCredentials } from './src/auto-detect.js';
import { nowISO } from '@sequential/sequential-utils/timestamps';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

function parseArgs() {
  const args = process.argv.slice(2);
  const config = {
    library: null,
    port: 3100,
    outputDir: './services',
    force: false
  };

  for (let i = 0; i < args.length; i++) {
    if (args[i] === '--port') {
      config.port = parseInt(args[++i]);
    } else if (args[i] === '--output') {
      config.outputDir = args[++i];
    } else if (args[i] === '--force' || args[i] === '-f') {
      config.force = true;
    } else if (!config.library && !args[i].startsWith('--')) {
      config.library = args[i];
    }
  }

  return config;
}

function generateServiceConfig(libraryName, port) {
  const credentials = detectCredentials(libraryName);

  return {
    library: libraryName,
    version: '1.0.0',
    description: `HTTP wrapper for ${libraryName} SDK`,
    port,
    initialization: {
      auto: true,
      timeout: 5000
    },
    credentials: credentials.reduce((acc, cred) => {
      acc[cred] = `keystore:${cred.toLowerCase()}`;
      return acc;
    }, {}),
    pause: {
      enabled: true,
      timeout: 30000,
      maxPayload: 1048576
    },
    retry: {
      enabled: true,
      maxAttempts: 3
    },
    cache: {
      enabled: false,
      ttl: 0
    },
    endpoints: {
      health: '/health',
      call: '/call'
    }
  };
}

function generateServiceCode(libraryName) {
  return `import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { processSdkRequest } from "https://esm.sh/sdk-http-wrapper/server";
import config from "./config.json" assert { type: "json" };

const handler = async (req) => {
  const url = new URL(req.url);

  if (req.method === "GET" && url.pathname === "/health") {
    return new Response(JSON.stringify({
      status: "ok",
      service: "${libraryName}",
      timestamp: nowISO()
    }), {
      status: 200,
      headers: { "Content-Type": "application/json" }
    });
  }

  if (req.method === "POST" && url.pathname === "/call") {
    const requestData = await req.json();
    const result = await processSdkRequest(requestData, config);

    return new Response(JSON.stringify(result.body), {
      status: result.status,
      headers: { "Content-Type": "application/json" }
    });
  }

  return new Response(JSON.stringify({ error: "Not found" }), {
    status: 404,
    headers: { "Content-Type": "application/json" }
  });
};

if (import.meta.main) {
  const port = parseInt(Deno.env.get("PORT") || "${3100}");
  serve(handler, { port });
  logger.info(\`[${libraryName}] Server listening on port \${port}\`);
}
`;
}

function generateDenoJson(libraryName) {
  return {
    tasks: {
      start: `deno run --allow-all --allow-env --allow-read --allow-write index.ts`,
      dev: `deno run --allow-all --allow-env --allow-read --allow-write --watch index.ts`
    },
    imports: {
      'sdk-http-wrapper/server': 'https://esm.sh/sdk-http-wrapper/server'
    }
  };
}

function generateReadme(libraryName, port) {
  return `# ${libraryName} SDK Wrapper

Auto-generated HTTP service wrapper for the \`${libraryName}\` SDK.

## Quick Start

### Start the Service

\`\`\`bash
deno run --allow-all --allow-env index.ts --port ${port}
\`\`\`

Or using the CLI:

\`\`\`bash
npx tasker --services ${libraryName}
\`\`\`

### Make a Request

\`\`\`bash
curl -X POST http://localhost:${port}/call \\
  -H "Content-Type: application/json" \\
  -d '{
    "chain": [
      {"type": "get", "property": "someMethod"},
      {"type": "call", "property": "someMethod", "args": [{}]}
    ],
    "config": {
      "module": "${libraryName}"
    }
  }'
\`\`\`

## Configuration

Edit \`config.json\` to customize:
- Credentials needed from keystore
- Pause/resume settings
- Retry behavior
- Response caching

## Credentials

This service requires the following credentials (stored in keystore):
\`\`\`
${detectCredentials(libraryName).map(c => `- ${c}`).join('\n')}
\`\`\`

Set them using the keystore service:

\`\`\`bash
curl -X POST http://localhost:3105/set-key \\
  -H "Content-Type: application/json" \\
  -d '{"key": "CREDENTIAL_NAME", "value": "credential_value"}'
\`\`\`

## Files

- \`index.ts\` - Service entry point
- \`config.json\` - Service configuration
- \`deno.json\` - Deno runtime configuration

## Auto-Generated

This service was auto-generated by \`wrap-sdk\` CLI.
Generated: ${nowISO()}
`;
}

async function createService(config) {
  const servicePath = path.join(config.outputDir, config.library);

  if (fs.existsSync(servicePath) && !config.force) {
    logger.error(`❌ Service directory already exists: ${servicePath}`);
    logger.error('   Use --force to overwrite');
    process.exit(1);
  }

  logger.info(`📁 Creating service directory: ${servicePath}`);
  fs.mkdirSync(servicePath, { recursive: true });

  try {
    const serviceConfig = generateServiceConfig(config.library, config.port);
    fs.writeFileSync(
      path.join(servicePath, 'config.json'),
      JSON.stringify(serviceConfig, null, 2)
    );
    logger.info('  ✅ config.json');

    const serviceCode = generateServiceCode(config.library);
    fs.writeFileSync(
      path.join(servicePath, 'index.ts'),
      serviceCode
    );
    logger.info('  ✅ index.ts');

    const denoJson = generateDenoJson(config.library);
    fs.writeFileSync(
      path.join(servicePath, 'deno.json'),
      JSON.stringify(denoJson, null, 2)
    );
    logger.info('  ✅ deno.json');

    const readme = generateReadme(config.library, config.port);
    fs.writeFileSync(
      path.join(servicePath, 'README.md'),
      readme
    );
    logger.info('  ✅ README.md');

    fs.writeFileSync(
      path.join(servicePath, '.gitignore'),
      'node_modules/\ndeno.lock\n.env\n'
    );
    logger.info('  ✅ .gitignore');

    logger.info(`\n✅ Service created successfully!\n`);
    logger.info(`📝 Next steps:`);
    logger.info(`\n1. Edit credentials in config.json`);
    logger.info(`\n2. Start the service:`);
    logger.info(`   cd ${servicePath}`);
    logger.info(`   deno run --allow-all --allow-env index.ts\n`);
    logger.info(`3. Or use with tasker CLI:`);
    logger.info(`   npx tasker --services ${config.library}\n`);
  } catch (error) {
    logger.error('❌ Failed to create service:', error.message);
    process.exit(1);
  }
}

async function main() {
  const args = parseArgs();

  if (!args.library) {
    logger.info(`
wrap-sdk - Zero-code SDK wrapping

Usage: npx wrap-sdk <library-name> [options]

Examples:
  npx wrap-sdk supabase
  npx wrap-sdk openai --port 3101
  npx wrap-sdk stripe --output ./my-services

Options:
  --port <number>      Base port for service (default: 3100)
  --output <dir>       Output directory (default: ./services)
  --force, -f          Overwrite existing service
  --help               Show this help message

Supported libraries (auto-detected):
  - supabase           Database + Auth
  - openai             LLM API
  - stripe             Payments
  - twilio             Communications
  - mongodb            NoSQL database
  - redis              Cache
  - elasticsearch      Search
  - anthropic          LLM API
  - And many more!
`);
    process.exit(0);
  }

  logger.info(`🔧 Creating zero-code wrapper for: ${args.library}\n`);
  await createService(args);
}

main().catch(err => {
  logger.error('❌ Error:', err.message);
  process.exit(1);
});
